import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Activity, BrainCircuit, Gauge } from "lucide-react";
import { motion } from "framer-motion";
import { Page } from "../components/layout/Page";
import { UrlForm } from "../components/scan/UrlForm";
import { ScanFailure, ScanState } from "../components/scan/ScanState";
import { useScan } from "../hooks/useScan";
export function Home() { const navigate = useNavigate(); const { loading, error, stage, run, clearError } = useScan(); const [submitted, setSubmitted] = useState(""); async function submit(url: string) { setSubmitted(url); const outcome = await run(url); if (outcome) navigate("/dashboard", { state: outcome }); } return <Page><main className="shell py-16 sm:py-24"><div className="grid gap-16 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><motion.section initial={{opacity:0,y:14}} animate={{opacity:1,y:0}}><p className="mb-5 font-mono text-xs uppercase tracking-[.2em] text-cyan-300">Engineering audit, not surface analytics</p><h1 className="max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">Know what is actually wrong with your website.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-slate-400">Scan performance, accessibility, SEO, browser behaviour and runtime issues with real browser data, Lighthouse and AI-powered engineering analysis.</p><div className="mt-9">{loading ? <ScanState url={submitted} stage={stage}/> : error ? <ScanFailure message={error.message} onRetry={() => submit(submitted)} onBack={clearError}/> : <UrlForm onSubmit={submit} disabled={loading}/>}</div><p className="mt-4 font-mono text-xs text-slate-600">Real browser telemetry · Lighthouse audits · AI engineering review</p></motion.section><aside className="panel p-6"><p className="font-mono text-xs uppercase tracking-wider text-slate-500">What DevLens observes</p><div className="mt-6 space-y-6">{[[Activity,"Browser behaviour","Console activity, network requests and runtime exceptions."],[Gauge,"Lighthouse evidence","Performance, accessibility, best practices and SEO."],[BrainCircuit,"Engineering interpretation","AI analysis grounded in the captured evidence."]].map(([Icon,title,body]) => { const I = Icon as typeof Activity; return <div className="flex gap-4" key={title as string}><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-cyan-300/10 text-cyan-300"><I size={18}/></span><div><h2 className="font-medium">{title as string}</h2><p className="mt-1 text-sm leading-relaxed text-slate-400">{body as string}</p></div></div>; })}</div></aside></div><section className="mt-24 border-t border-white/10 pt-10"><p className="font-mono text-xs uppercase tracking-[.16em] text-slate-500">How it works</p><div className="mt-6 grid gap-6 sm:grid-cols-3">{[["01","Enter URL","Give DevLens a public website address."],["02","A real browser scans","Telemetry and Lighthouse evidence are captured."],["03","Review the report","Use evidence and recommendations to prioritize fixes."]].map(([number,title,body]) => <div key={number}><p className="font-mono text-cyan-300">{number}</p><h2 className="mt-2 font-medium">{title}</h2><p className="mt-2 text-sm leading-relaxed text-slate-400">{body}</p></div>)}</div></section></main></Page>; }
