import { useMemo, useState } from "react";
import { ChevronDown, ExternalLink, Search } from "lucide-react";
import { assetUrl } from "../../services/api";
import type { Audit, ConsoleLog, Exception, Issue, NetworkRequest } from "../../types/scan";

const status = (score: number) => score >= 90 ? ["Excellent", "text-emerald-300"] : score >= 75 ? ["Healthy", "text-cyan-300"] : score >= 50 ? ["Needs attention", "text-amber-300"] : ["Critical", "text-rose-300"];
export function ScoreCard({ title, score }: { title: string; score: number }) { const [label, color] = status(score); return <article className="panel p-4"><p className="text-xs font-medium uppercase tracking-wider text-slate-500">{title}</p><div className="mt-4 flex items-end justify-between"><p className="text-3xl font-semibold">{Math.round(score)}<span className="text-sm font-normal text-slate-500">/100</span></p><span className={`text-xs ${color}`}>{label}</span></div><div className="mt-4 h-1 overflow-hidden rounded bg-white/10"><div className="h-full rounded bg-cyan-300" style={{width: `${Math.max(0, Math.min(100, score))}%`}}/></div></article>; }
export function Screenshot({ path }: { path?: string }) { const [failed, setFailed] = useState(false); return <section><Heading title="Captured screenshot" detail="Raw scan data"/>{!path || failed ? <Empty text="Screenshot unavailable."/> : <div className="panel overflow-hidden"><img className="min-h-48 w-full bg-slate-950 object-contain" src={assetUrl(path)} alt="Captured website screenshot" onError={() => setFailed(true)}/><a className="flex items-center gap-2 border-t border-white/10 px-4 py-3 text-sm text-cyan-300" href={assetUrl(path)} target="_blank" rel="noreferrer">Open full image <ExternalLink size={14}/></a></div>}</section>; }
export function Issues({ issues }: { issues: Issue[] }) { const [filter, setFilter] = useState("all"); const shown = issues.filter(issue => filter === "all" || issue.severity === filter); return <section><Heading title="Issues" detail="AI engineering interpretation"/><div className="mb-4 flex flex-wrap gap-2">{["all", "critical", "high", "medium", "low"].map(value => <button key={value} onClick={() => setFilter(value)} className={`rounded-md px-3 py-1.5 text-xs capitalize ${filter === value ? "bg-cyan-300 text-slate-950" : "bg-white/5 text-slate-400"}`}>{value}</button>)}</div>{shown.length ? <div className="space-y-3">{shown.map((issue, index) => <IssueRow key={`${issue.title}-${index}`} issue={issue}/>)}</div> : <Empty text={issues.length ? "No issues match this filter." : "No issues were reported for this scan."}/>}</section>; }
function IssueRow({ issue }: { issue: Issue }) { const [open, setOpen] = useState(issue.severity === "critical" || issue.severity === "high"); const tone = issue.severity === "critical" ? "text-rose-300 bg-rose-400/10" : issue.severity === "high" ? "text-orange-300 bg-orange-400/10" : issue.severity === "medium" ? "text-amber-300 bg-amber-400/10" : "text-sky-300 bg-sky-400/10"; return <article className="panel"><button className="flex w-full items-center gap-3 p-4 text-left" onClick={() => setOpen(!open)} aria-expanded={open}><span className={`rounded px-2 py-1 text-[11px] font-semibold uppercase ${tone}`}>{issue.severity}</span><span className="text-xs text-slate-500">{issue.category}</span><span className="min-w-0 flex-1 font-medium">{issue.title}</span><ChevronDown className={open ? "rotate-180" : ""} size={16}/></button>{open && <div className="grid gap-4 border-t border-white/10 p-4 text-sm text-slate-400 sm:grid-cols-2"><Field label="Evidence" value={issue.evidence?.trim() || "Evidence not provided by scan."}/><Field label="Description" value={issue.description}/><Field label="Impact" value={issue.impact}/><Field label="Recommendation" value={issue.recommendation}/></div>}</article>; }
export function Findings({ audits }: { audits: Audit[] }) { return <section><Heading title="Lighthouse findings" detail="Raw Lighthouse findings"/>{audits.length ? <div className="space-y-2">{audits.map(audit => <details className="panel p-4" key={audit.id}><summary className="cursor-pointer list-none"><span className="font-mono text-xs text-cyan-300">{audit.id}</span><span className="ml-3 font-medium">{audit.title}</span><span className="float-right text-sm text-slate-400">{Math.round(audit.score * 100)}/100</span></summary><p className="mt-3 text-sm text-slate-400">{audit.description}</p></details>)}</div> : <Empty text="No failed Lighthouse audits were reported."/>}</section>; }
export function Network({ requests }: { requests: NetworkRequest[] }) { const [query, setQuery] = useState(""); const rows = useMemo(() => requests.filter(row => `${row.method} ${row.status} ${row.url}`.toLowerCase().includes(query.toLowerCase())), [query, requests]); return <section><Heading title="Network requests" detail={`${requests.length} request${requests.length === 1 ? "" : "s"} captured`}/>{requests.length ? <div className="panel overflow-x-auto"><div className="border-b border-white/10 p-3"><label className="flex max-w-sm items-center gap-2 rounded-md bg-white/5 px-3"><Search size={14}/><input className="w-full bg-transparent py-2 text-sm outline-none" value={query} onChange={e => setQuery(e.target.value)} placeholder="Filter requests"/></label></div><table className="min-w-full text-left font-mono text-xs"><thead className="text-slate-500"><tr><th className="p-3">Method</th><th className="p-3">Status</th><th className="p-3">URL</th></tr></thead><tbody>{rows.map((row, index) => <tr className="border-t border-white/5" key={`${row.url}-${index}`}><td className="p-3">{row.method || "—"}</td><td className={`p-3 ${(row.status || 0) >= 400 ? "text-rose-300" : "text-emerald-300"}`}>{row.status ?? "—"}</td><td className="max-w-[34rem] truncate p-3 text-slate-400" title={row.url}>{row.url || "—"}</td></tr>)}</tbody></table></div> : <Empty text="No network requests were captured."/>}</section>; }
export function Logs({ logs, exceptions }: { logs: ConsoleLog[]; exceptions: Exception[] }) { return <div className="grid gap-8 lg:grid-cols-2"><section><Heading title="Console logs" detail={`${logs.length} entries captured`}/>{logs.length ? <div className="panel max-h-80 overflow-auto p-3 font-mono text-xs">{logs.map((log, index) => <p key={index} className="border-b border-white/5 py-2 text-slate-400"><span className="mr-2 text-cyan-300">{log.type || log.level || "log"}</span>{log.text || log.message || JSON.stringify(log)}</p>)}</div> : <Empty text="No console logs were captured."/>}</section><section><Heading title="Runtime exceptions" detail={`${exceptions.length} captured`}/>{exceptions.length ? <div className="space-y-2">{exceptions.map((exception, index) => <div className="panel border-rose-500/30 p-4 font-mono text-sm" key={index}><p>{exception.message || "Unspecified runtime exception"}</p>{exception.source && <p className="mt-2 text-xs text-slate-500">{exception.source}</p>}{exception.stack && <pre className="mt-3 overflow-auto text-xs text-slate-400">{exception.stack}</pre>}</div>)}</div> : <Empty text="0 runtime exceptions"/>}</section></div>; }
function Heading({ title, detail }: { title: string; detail: string }) { return <div className="mb-4"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-slate-500">{detail}</p></div>; }
function Field({ label, value }: { label: string; value?: string }) { return <div><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 leading-relaxed">{value || "Not provided by scan."}</p></div>; }
export function Empty({ text }: { text: string }) { return <div className="panel p-5 text-sm text-slate-400">{text}</div>; }
